version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/jakepearson/webbing
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: docker build -t webbing .